language: node_js
node_js:
  - "6"
script:
- npm rebuild node-sass # https://github.com/sass/node-sass/issues/1579
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ./build
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master