language: node_js
node_js:
  - "6"
# before_script:
#  - npm install
script:
- nodejs node_modules/node-sass/scripts/install.js
- npm rebuild node-sass
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ./build
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master