language: node_js
node_js:
  - "6"
before_script:
 - npm install
script:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ./public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master